name: Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: theos/setup-theos@master
      - run: make package
      - uses: actions/upload-artifact@v3
        with:
          name: AlfieClient
          path: packages/*.deb
