name: Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: theos/setup-theos@master
      - name: Build Package
        working-directory: ./template
        run: make package FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: AlfieClient
          path: template/packages/*.deb
